version: '3.8'

services:
  postgres:
    image: postgres:12.19-alpine3.20
    restart: always
    environment:
      - POSTGRES_USER=iarylser
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=iarylser
    ports:
      - '5432:5432'
  redis:
    image: redis:alpine3.20
    restart: always
    ports:
      - '6379:6379'
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_DIR=/app
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      - redis