name: CI Pipeline

on:
  workflow_dispatch:
    inputs:
      scan:
        description: 'Scan'
        required: true
        default: 'true'
        type: boolean
      build:
        description: 'Build the project'
        required: true
        default: 'true'
        type: boolean
      test:
        description: 'Run tests'
        required: true
        default: 'true'
        type: boolean

jobs:
  build:
    needs: scan
    if: ${{ github.event.inputs.build == 'true' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build -x test

  test:
    needs: build
    if: ${{ github.event.inputs.test == 'true' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Run tests
      run: ./gradlew test
  scan:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   
        TokengeneratedSONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL}}
